version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github_actions"
      - "Skip Changelog"
    ignore:
      # Ignore all patch releases as we can manually
      # upgrade if we run into a bug and need a fix.
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
