version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Combine all Actions updates into one pull request.
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "Skip Changelog"
    cooldown:
      default-days: 7
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "quarterly"
    # Combine all pre-commit hook updates into one pull request.
    groups:
      pre-commit:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "Skip Changelog"
    cooldown:
      default-days: 7
