version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - brotli
        - secure
        - socks
    - requirements: docs/requirements.txt

sphinx:
  fail_on_warning: true
