version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - brotli
        - secure
        - socks
        - zstd

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
