version: 2

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - brotli
        - secure
        - socks

sphinx:
  fail_on_warning: true
