version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  create_environment:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
  install:
    - uv sync --group docs --extra brotli --extra socks --extra zstd

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
