name: "Scorecard"
on:
  branch_protection_rule:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ["main"]

permissions:
  contents: "read"

jobs:
  analysis:
    if: github.repository_owner == 'urllib3'
    name: "Scorecard"
    runs-on: "ubuntu-latest"
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Run Scorecard"
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: true
